- hosts: all
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
  - name: Creates the remote directory
    file:
      state: directory
      recurse: yes
      path: "{{ remote_dir }}"
  - name: Installs the new facts
    copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"
