---
- name: Create users
  hosts: mnode1
  vars_files:
    - test.yml
  tasks:
  - name: Creating users from test.yml
    user: 
      name: "{{ item.name }}"
      password: "{{ item.pw | password_hash('sha512') }}"
    with_items: "{{ newusers }}"
