---
- hosts: all
  vars:
    maildir_path: /home/vagrant/
    maildir: /home/jonathan/
    mail_package: postfix
    mail_service: postfix
  tasks:
  - block:
    - name: Create {{ maildir_path }}
      copy: 
       src: "{{ maildir_path }}"
       dest: "{{ maildir }}"
       mode: 0755
    rescue:
    - name: Install mail packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ mail_package }}"
        - dovecot
    always:
    - name: start mail services
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - "{{ mail_service }}"
        - dovecot
      register: command_result
  - debug:
      var:  command_result.msg
