- hosts: mnode1
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: first task
      yum:
        name: httpd
        state: latest
    - name: second task
      yum:
        name: openssh-server
        state: latest
    - name: third task
      service:
        name: httpd
        enabled: true
        state: started
    - name: fourth task
      service: 
        name: sshd
        enabled: true
        state: started
