---
- hosts: all
  tasks:
  - name: Imports the variables file
    include_vars: vars/demovars_includevars.yml
  - name: Creates the remote directory
    file:
      path: "{{ paths.fileserver }}"
      state: directory
      mode: 0755
    register: result
 - name: Debugs the results
   debug:
     var: result
