##Playbook Conditionals
---
- hosts: mnode11
  vars:
     mail_services:
        - postfix
        - dovecot
     alpha: [ 'a', 'b', 'c', 'd', 'e']
     numbers: [ 1, 2, 3, 4 ]
  tasks:
  - name: Install postfix
    yum: 
       name: postfix
       state: latest
    tags:
      - normal
  - name: Install dovecot
    yum: 
       name: dovecot
       state: latest
    tags:
      - normal

  - name: Install packages using with_items loop
    yum:
       name: "{{ item }}"
       state: latest
    with_items:
       - postfix
       - dovecot
    tags:
      - withitems

  - name: Install packages using loop and variables
    yum:
       name: "{{ item }}"
       state: latest
    with_items: "{{ mail_services }}"
    tags: 
      - withitems1


  - name: copy files to different sources and different dests using loops
    copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
    with_items:
       - { src: '~/ktx/syllabus.txt', dest: '/home/vagrant/test1.txt'}
       - { src: '~/ktx/KTX/ktxhosts/myhosts', dest: '/tmp/test2.txt'}
    tags:
       - withitems2

  - name: Read lines using with_lines
    debug: 
       msg: "I am from file {{ item }}"
    with_lines:
       - cat ~/ktx/syllabus.txt
    tags:
      - withlines

  - name: List out files with_fileglob
    copy: 
       src: "{{ item }}" 
       dest: "/tmp/"
    with_fileglob:
        - ~/ktx/KTX/playbooks/*yml
    tags:
      - withfileglob

  - name: Looping over parallel sets of data
    debug: 
       msg: "{{ item.0 }} and {{ item.1 }}"
    with_together:
       - "{{ alpha }}"
       - "{{ numbers }}"
    tags:
      - withtogether
       
  - name: Print Hello to Jonathan
    debug:
      msg: " Hello Jonathan"
    tags:
     - always 
