---
- name: Install APACHE in CNODE
  hosts: cnode
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest

- name: Install POSTGRESQL in MNODE1
  hosts: mnode1
  tasks:
  - name: ensure postgresql is at the latest version
    yum: name=postgresql state=latest
