- name: Task vars example
  hosts: mnode1
  tasks:
  - name: Include CopyVars file 
    include_vars: copyvars

  - name: Copy hosts file to /tmp directory
    copy: 
      src: "{{SOURCE}}"
      dest: "{{DESTINATION}}"
