---
- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    bucketname: rgodishela_yan001
  tasks:
    - name: create an S3 bucket
      s3:
        bucket: "{{ bucketname }}"
        mode: create
